# Generated by Django 5.2.1 on 2025-05-30 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificado_existencia', models.FileField(blank=True, null=True, upload_to='certificados_empresa/')),
                ('rut', models.FileField(blank=True, null=True, upload_to='certificados_empresa/')),
                ('nit', models.CharField(max_length=30)),
                ('acta_constitucion', models.FileField(blank=True, null=True, upload_to='certificados_empresa/')),
                ('ubicaciones', models.TextField(blank=True, help_text='Direcciones de los locales, separadas por comas o en lista.')),
            ],
        ),
    ]
