# Generated by Django 5.2.1 on 2025-05-30 01:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteCandidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hoja_vida', models.FileField(blank=True, null=True, upload_to='hojas_vida/')),
                ('certificados_discapacidad', models.FileField(blank=True, null=True, upload_to='certificados_discapacidad/')),
                ('certificados_estudio', models.FileField(blank=True, null=True, upload_to='certificados_estudio/')),
                ('datos_extra', models.CharField(blank=True, max_length=255)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('profesion', models.CharField(max_length=100)),
                ('experiencia', models.TextField(blank=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
